<?php

$config = array(
	'entities'=>array(
		'Project'=>array(
			'name'=>'Project',
			'properties'=>array(
				'id',
				'name',
				'description',
				'type'
			),
			'relations'=>array(
				'parents'=>array(
					'type'=>array(
						'entity'=>'Type',
						'type'=>'one-to-many',
						'foreignKey'=>'type'
					)
				)
			)
		),
		'Type'=>array(
			'name'=>'Type',
			'properties'=>array(
				'id',
				'type'
			),
			'relations'=>array(
				'dependents'=>array(
					'parent'=>array(
						'entity'=>'Parent',
						'type'=>'many-to-one',
						'foreignKey'=>'type'
					)
				)
			)
		)
	)
);